# Generated by Django 4.1 on 2022-08-10 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_cinema'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cinema',
        ),
    ]
