# Generated by Django 4.1 on 2022-08-10 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_delete_cinema'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('descriptions', models.TextField(max_length=200)),
                ('year', models.IntegerField()),
                ('janr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='janrs', to='cinema.category')),
            ],
        ),
    ]
