# Generated by Django 4.1 on 2022-08-10 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview', models.ImageField(upload_to='cinema')),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preview', to='cinema.cinema')),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
