# Generated by Django 4.1 on 2022-08-10 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0008_alter_cinema_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinema',
            name='avatar',
        ),
    ]
