# Generated by Django 4.1 on 2022-08-13 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cinema', '0011_rename_preview_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False, verbose_name='лайк')),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes1', to=settings.AUTH_USER_MODEL, verbose_name='фильм')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='Владелей лайка')),
            ],
        ),
    ]
