# Generated by Django 4.1 on 2022-08-13 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cinema', '0012_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='cinema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_cinema', to=settings.AUTH_USER_MODEL, verbose_name='фильм'),
        ),
    ]
