# Generated by Django 4.1 on 2022-08-14 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0019_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
