# Generated by Django 4.1 on 2022-08-15 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0022_alter_favorite_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cinema',
            old_name='avatar',
            new_name='images',
        ),
    ]
