# Generated by Django 4.1 on 2022-08-15 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0023_rename_avatar_cinema_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='preview',
            new_name='image',
        ),
    ]
