# Generated by Django 4.1 on 2022-08-15 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0024_rename_preview_image_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cinema',
            old_name='images',
            new_name='avatar',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='preview',
        ),
    ]
