# Generated by Django 4.1 on 2022-08-15 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0025_rename_images_cinema_avatar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinema',
            name='avatar',
        ),
    ]
