# Generated by Django 4.1 on 2022-08-15 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0026_remove_cinema_avatar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Preview',
        ),
    ]
