# Generated by Django 4.1 on 2022-08-16 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0028_rename_preview_preview_image_alter_preview_cinema'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='video/')),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='cinema.cinema')),
            ],
        ),
    ]
